[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "flare-foundry-periphery-package/=lib/flare-foundry-periphery-package/src/",
]
optimizer = true
optimizer_runs = 200
via_ir = true
gas_limit = 5000000
evm_version = "london"

[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/C/rpc"
